<?php
$z[0]=Array("field","",66,85);
$z[0][4]['name']="title";
$z[1]=Array("global","",86,112);
$z[1][4]['name']="cfg_webname";
$z[2]=Array("field","",153,182);
$z[2][4]['name']="keywords";
$z[3]=Array("field","",222,280);
$z[3][4]['name']="description";
$z[3][4]['function']="html2text(@me)";
$z[4]=Array("include","",808,843);
$z[4][4]['filename']="head.htm";
$z[5]=Array("field","",1624,1646);
$z[5][4]['name']="position";
$z[6]=Array("field","",1819,1841);
$z[6][4]['name']="typename";
$z[7]=Array("productimagelist"," \r\n                <li><a href=\"[field:imgsrc/]\"><img src=\"[field:imgsrc/]\" title=\"[field:text/]\" width=\"150\" height=\"79\" /></a></li>\r\n                ",2342,2540);
$z[8]=Array("prenext","",3501,3526);
$z[8][4]['get']="pre";
$z[9]=Array("prenext","",3571,3597);
$z[9][4]['get']="next";
$z[10]=Array("include","",3722,3757);
$z[10][4]['filename']="foot.htm";

?>