<?php
$z[0]=Array("field","",66,85);
$z[0][4]['name']="title";
$z[1]=Array("global","",86,112);
$z[1][4]['name']="cfg_webname";
$z[2]=Array("field","",153,182);
$z[2][4]['name']="keywords";
$z[3]=Array("field","",222,280);
$z[3][4]['name']="description";
$z[3][4]['function']="html2text(@me)";
$z[4]=Array("include","",805,840);
$z[4][4]['filename']="head.htm";
$z[5]=Array("field","",1621,1643);
$z[5][4]['name']="position";
$z[6]=Array("productimagelist"," \r\n                  <figure> <a href=\"[field:imgsrc/]\"> <img src=\"[field:imgsrc/]\" alt=\"\" width=\"400\" height=\"300\" /> </a>\r\n                    <figcaption></figcaption>\r\n                  </figure>\r\n                  ",2026,2292);
$z[7]=Array("productimagelist"," \r\n                <li><img src=\"[field:imgsrc/]\" alt=\"\" width=\"70\" height=\"70\" /></li>\r\n               ",2414,2565);
$z[8]=Array("field","",2747,2766);
$z[8][4]['name']="title";
$z[9]=Array("field","",2832,2849);
$z[9][4]['name']="axh";
$z[10]=Array("field","",2895,2912);
$z[10][4]['name']="app";
$z[11]=Array("field","",2958,2975);
$z[11][4]['name']="ajg";
$z[12]=Array("field","",3299,3317);
$z[12][4]['name']="body";
$z[13]=Array("prenext","",4060,4085);
$z[13][4]['get']="pre";
$z[14]=Array("prenext","",4130,4156);
$z[14][4]['get']="next";
$z[15]=Array("likeart","\r\n          <li> <a href=\"[field:arcurl/]\" title=\"[field:title /]\" target='_self'> <img src=\"[field:litpic/]\" width =\"213\" height=\"160\" />\r\n            <h2>[field:title /]</h2>\r\n            </a> </li>\r\n            ",4299,4564);
$z[15][4]['row']="2";
$z[15][4]['titlelen']="36";
$z[16]=Array("include","",4666,4701);
$z[16][4]['filename']="foot.htm";

?>