<?php
$z[0]=Array("global","",82,108);
$z[0][4]['name']="cfg_powerby";
$z[1]=Array("global","",111,135);
$z[1][4]['name']="cfg_beian";
$z[2]=Array("type"," <a href='[field:typelink /]'  title='[field:typename /]'>[field:typename /]</a> ",256,371);
$z[2][4]['typeid']="1";
$z[3]=Array("type"," <a href='[field:typelink /]'  title='[field:typename /]'>[field:typename /]</a> ",387,503);
$z[3][4]['typeid']="17";

?>