<?php
$z[0]=Array("global","",161,187);
$z[0][4]['name']="cfg_webname";
$z[1]=Array("global","",286,307);
$z[1][4]['name']="cfg_dh";
$z[2]=Array("global","",455,481);
$z[2][4]['name']="cfg_webname";
$z[3]=Array("global","",537,563);
$z[3][4]['name']="cfg_webname";
$z[4]=Array("global","",572,598);
$z[4][4]['name']="cfg_webname";
$z[5]=Array("global","",736,761);
$z[5][4]['name']="cfg_cmsurl";
$z[6]=Array("channelartlist","\r\n        <li> <a href=\"{dede:field name='typeurl'/}\"  title=\"{dede:field name='typename'/}\">{dede:field name='typename'/}</a>\r\n          <dl>\r\n            {dede:channel type='son' noself='yes'}\r\n            <dd> <a href=\"[field:typelink/]\"  title=\"[field:typename/]\">[field:typename/]</a> </dd>\r\n            {/dede:channel}\r\n          </dl>\r\n        </li>\r\n        ",1302,1731);
$z[6][4]['row']="10";
$z[6][4]['typeid']="top";

?>