<?php
$z[0]=Array("field","",66,85);
$z[0][4]['name']="title";
$z[1]=Array("global","",86,112);
$z[1][4]['name']="cfg_webname";
$z[2]=Array("field","",153,182);
$z[2][4]['name']="keywords";
$z[3]=Array("field","",222,280);
$z[3][4]['name']="description";
$z[3][4]['function']="html2text(@me)";
$z[4]=Array("include","",803,838);
$z[4][4]['filename']="head.htm";
$z[5]=Array("type","[field:typename /]",1640,1692);
$z[5][4]['typeid']="4";
$z[6]=Array("channelartlist","\r\n        <dl class=\"list-none navnow\">\r\n          <dt id='part2_25' {dede:field name='currentstyle'/}><a href='{dede:field name='typeurl'/}' class=\"zm\"><span>{dede:field name='typename'/}</span></a></dt>\r\n        </dl>\r\n        ",1743,2050);
$z[6][4]['type']="son";
$z[6][4]['noself']="yes";
$z[6][4]['typeid']="4";
$z[7]=Array("field","",2263,2285);
$z[7][4]['name']="typename";
$z[8]=Array("field","",2327,2349);
$z[8][4]['name']="position";
$z[9]=Array("list","\r\n          <li class=\"list_1\">\r\n            <h2><a href=\"[field:arcurl/]\" title=\"[field:title/]\" target='_self'><i class=\"fa fa-caret-right\"></i>[field:title/]</a></h2>\r\n            <span class='time'>[field:pubdate function='strftime(\"%Y-%m-%d\",@me)'/]</span> </li>\r\n          ",2475,2791);
$z[9][4]['pagesize']="15";
$z[10]=Array("pagelist","",2859,2925);
$z[10][4]['listitem']="index,end,pre,next,pageno";
$z[10][4]['listsize']="5";
$z[11]=Array("include","",3006,3041);
$z[11][4]['filename']="foot.htm";

?>