<?php
$z[0]=Array("field","",66,85);
$z[0][4]['name']="title";
$z[1]=Array("global","",86,112);
$z[1][4]['name']="cfg_webname";
$z[2]=Array("field","",153,182);
$z[2][4]['name']="keywords";
$z[3]=Array("field","",222,280);
$z[3][4]['name']="description";
$z[3][4]['function']="html2text(@me)";
$z[4]=Array("include","",806,841);
$z[4][4]['filename']="head.htm";
$z[5]=Array("field","",1714,1736);
$z[5][4]['name']="typename";
$z[6]=Array("field","",1778,1800);
$z[6][4]['name']="position";
$z[7]=Array("list","\r\n          <li> <a href=\"[field:arcurl/]\" title=\"[field:title/]\" target='_self'> <img src=\"[field:litpic/]\" width =\"200\" height=\"150\" />\r\n            <h2>[field:title/]</h2>\r\n            </a> </li>\r\n          ",1944,2205);
$z[7][4]['pagesize']="20";
$z[7][4]['titlelen']="36";
$z[8]=Array("pagelist","",2290,2356);
$z[8][4]['listitem']="index,end,pre,next,pageno";
$z[8][4]['listsize']="5";
$z[9]=Array("include","",2451,2486);
$z[9][4]['filename']="foot.htm";

?>