<?php
$z[0]=Array("field","",66,85);
$z[0][4]['name']="title";
$z[1]=Array("global","",86,112);
$z[1][4]['name']="cfg_webname";
$z[2]=Array("field","",153,182);
$z[2][4]['name']="keywords";
$z[3]=Array("field","",222,280);
$z[3][4]['name']="description";
$z[3][4]['function']="html2text(@me)";
$z[4]=Array("include","",1213,1248);
$z[4][4]['filename']="head.htm";
$z[5]=Array("type","[field:typename /]",2051,2104);
$z[5][4]['typeid']="15";
$z[6]=Array("channelartlist","\r\n        <dl class=\"list-none navnow\">\r\n          <dt id='part2_25' {dede:field name='currentstyle'/}><a href='{dede:field name='typeurl'/}' class=\"zm\"><span>{dede:field name='typename'/}</span></a></dt>\r\n        </dl>\r\n        ",2155,2463);
$z[6][4]['type']="son";
$z[6][4]['noself']="yes";
$z[6][4]['typeid']="15";
$z[7]=Array("field","",2676,2698);
$z[7][4]['name']="typename";
$z[8]=Array("field","",2740,2762);
$z[8][4]['name']="position";
$z[9]=Array("include","",3823,3858);
$z[9][4]['filename']="foot.htm";

?>